# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# https://goreleaser.com/customization/build/
project_name: iconhash
gomod:
  proxy: true
builds:
  - env: [CGO_ENABLED=0]
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - -s -w -X main.build={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates: ["becivells/iconhash:{{ .Version }}"]
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/becivells/iconhash
      - --label=org.opencontainers.image.source=https://github.com/becivells/iconhash
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
nfpms:
  - maintainer: becivells <becivells@qq.com>
    description: fofa shodan iconhash
    homepage: https://github.com/becivells/iconhash
    license: MIT
    formats:
      - deb
      - rpm