# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# https://goreleaser.com/customization/build/
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - -s -w -X main.build={{.Version}}
    ignore:
      - goos: darwin
        goarch: 386
    goos:
      - linux
      - darwin
      - windows
      - netbsd
      - openbsd
      - plan9
      - solaris
      - freebsd
    gobinary: "go1.13.4"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      netbsd: NetBSD
      openbsd: OpenBSD
      plan9: Plan9
      solaris: Solaris
      freebsd: FreeBSD
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'