name: bats test

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
      -
        name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: install bats
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          sudo add-apt-repository ppa:duggan/bats --yes
          sudo apt-get update -qq
          sudo apt-get install -qq bats
      - name: test bats
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          make
          make test-cli

